name: {$PracticeWork}
main: {$practicework}.{practicework}
version: {1}
commands:
   basic:
      description: This is a demo command.
      usage: /basic [player]
      permission: practicework.basic
      permission-message: You don't have <permission>